### ISSUE TITLE
Feature Request - Take a server snapshot

### ISSUE THREAD

**Issue by byparallax** [JRoy/discord-themer#1]
Heya! I am posting this feature request to the official repository, after being redirected from [this reddit thread](https://www.reddit.com/r/discordapp/comments/849c55/i_wrote_an_easytouse_themer_for_discord_in_java/).

I'd like to have an easier option than creating the theme myself, by being able to setup my server and customize it within the app in a first time. Then, after loading a specific process of the bot it would take a ""snapshot"" of my server that will be saved as a theme. This process should make the bot much more user friendly and therefore help the spreading of this wonderful idea.

Thanks!

**Comment by WheezyGold7931** [comment]
Will add a method to export the server's current look to a theme file. Would it make sense to add this to the list of active themes or just create the file?

**Comment by WheezyGold7931** [comment]
Okay

**Comment by JRoy** [comment]
@byparallax This feature has been added in 1.1 and is ready for use

**Comment by byparallax** [comment]
Neat!

2018-03-24 0:21 GMT+01:00 Josh Roy <notifications@github.com>:
